version: "3.3"

services:
  api:
    build: ./backend
    environment:
      - CONNECTION_STRING=postgres://vishal:vishal@db/mydb
    depends_on:
      - db
    networks:
      - network-backend
      - network-frontend

  webapp:
    build: ./frontend
    environment:
      - API_URL=http://api:3001/data
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-frontend

  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: vishal
      POSTGRES_PASSWORD: vishal
      POSTGRES_DB: mydb
    volumes:
      - ./init_sql_scripts/:/docker-entrypoint-initdb.d
    networks:
      - network-backend

networks:
  network-backend:
  network-frontend:
